### ISSUE TITLE
Block sending empty comments

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#100]
**Describe the bug**
If I am clicked a send button, but no writed a comments it comment will be send.

**To Reproduce**
1. Open any topic.
2. Click send button next to comment.
3. Empty comment has been send.

**Expected behavior**
Should visible a message "You can not send empty comment. Please write a comment and try again"

**Screenshots**
![koment](https://user-images.githubusercontent.com/46194605/50759942-b9855d00-1266-11e9-845e-94b31abf6798.png)

**Desktop (please complete the following information):**
- Google Chrome 71.0.3578.98 on openSUSE Tumbleweed
- Firefox 64 on openSUSE Tumbleweed.

**Smartphone (please complete the following information):**
I am have not testin on mobile devices.

**Comment by Horndev** [comment]
fixed in https://github.com/Horndev/zapread.com/commit/3fe937c705205c46b4a433d55669c6c6e52e4119
