### ISSUE TITLE
History editing comments and block editing comments

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#101]
Zapread.com allows editing sended comments, but:

- the editing time should be visible so to let users know that it was editing. 
- maybe can add history comment and post editing? Something like a git?
- the comments editing  should be a blocked after replay. If any user replay on your comment or user writed a comment below comment editing should be blocked.

**Comment by Horndev** [comment]
Comment edit time is now visible.

History of comment version is too much effort at this time.  It may be considered in a future version once other more important features are implemented.

Comment editing could be blocked.  I will open a new issue with that: https://github.com/Horndev/zapread.com/issues/203
