### ISSUE TITLE
Function read more at long posts

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#102]
If user add a long post should visible button "Read more" and the rest of text it should be hidden. Currently users a reporting that such topics a  unnecessary lengthen the page.

You have to screenshot from polish social media service (wykop.pl), where the function was implemented read more.

**Before clicked a Read more button:**
![before_read_more](https://user-images.githubusercontent.com/46194605/50765358-f573ee80-1275-11e9-9c49-2e67a052c204.png)

**After clicked a Read more button:**
![after_read_more](https://user-images.githubusercontent.com/46194605/50765365-fa38a280-1275-11e9-98c2-56faab41ed3b.png)

**Comment by Horndev** [comment]
Thanks,

Is the read more not working correctly?  It should already be implemented.

**Comment by DocBox12** [comment]
Working, but too much text is a visible in my opinion.

![read_more](https://user-images.githubusercontent.com/46194605/50832478-9e8e1800-134e-11e9-8ce3-c0f893a49c92.png)

**Comment by Horndev** [comment]
use https://css-tricks.com/text-fade-read-more/ approach?

**Comment by DocBox12** [comment]
It looks interesting. Use it, we will see how it goes.

**Comment by Horndev** [comment]
Should now be working.
