### ISSUE TITLE
The user should lose less reputation if he is downvoted by a user with a worse reputation.

### ISSUE THREAD

**Issue by fervi** [Horndev/zapread.com#104]
Hello, I noticed trolling, which consists in downvoting entries (including mine). In my opinion, if I have a higher reputation than a troll, I should lose fewer reputation points.

**Comment by fervi** [comment]
I invent something like this. It should works if (for example my) reputation of flagged user has bigger than flagger (??)

```
<?php

$flagged_reputation = 162562; // Fervi
$flagger_reputation = 77017; // Zelgada (for example xd)
$satoshi_reduce = 10000; // Someone spend 10k satoshi to reduce reputation of Fervi

$flagged_reputation = $flagged_reputation - $satoshi_reduce*(1/($flagged_reputation / $flagger_reputation));
echo $flagged_reputation;
```

**Comment by Horndev** [comment]
Anonymous voters will change score by 50% of amount spent

**Comment by Horndev** [comment]
Reputation system is now implemented.
