### ISSUE TITLE
Reconstruction private messages and notification from posts

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#111]
After implement notification about comments and private messages it made a mess. Private messages are mixed with notification and users can not founded the needed information. We are should think about extension and improvement of this system.

First we are should split private messages from notification come from posts. On the left site have a users with started a converstations, on the right site there is a conversation window. Private messages should have an options:

- conservations archive
- blocked users
- sending photos

If we have a module private messages should be created a separate icon. After the click we will be a moved on a separate website and new icon should show only notifications about new messages. You can use icon what is.

I do not know how reconstruct notification from posts. Generally notifications and private messages requires reconstruction because all is in one place. I would like to start a discussion on this subject under this post.

BTW Sorry for my english.

**Comment by Horndev** [comment]
Yes, the messaging features are very weak right now.  It was the most recent part of the website that was added.

I am already working on fixing the private messages :)

You can see an early prototype at https://www.zapread.com/Messages/Chat/{username}

where {username} is someone you are chatting with.

There is still lots of work to do.

I also like the idea to block users from sending private messages.  See https://github.com/Horndev/zapread.com/issues/116 

I really appreciate all of your input - it's helping make ZapRead a better website for everyone!

**Comment by Horndev** [comment]
activity stream for alerts?

**Comment by Horndev** [comment]
Need to clarify what is a message and what is an alert.

Alert:
- New Post in subscribed
- Withdraw made
- Deposit made

Messages (User interactions):
- Comment reply
- Private Messages

**Comment by Horndev** [comment]
Chats and messages now much improved.  Alerts are next.

**Comment by Horndev** [comment]
Bulk of this is now done.  Need to do some pretty-up, but it is functional.
