### ISSUE TITLE
Robohash avatars?

### ISSUE THREAD

**Issue by fervi** [Horndev/zapread.com#117]
Avatars generated by this generator used in Zapread are probably ugly, can you use Robohash (ofc. check license etc)?

Zelgada:
https://robohash.org/zelgada

Fervi:
https://robohash.org/fervi

**Comment by Horndev** [comment]
Cool!  That would be nicer.  I can do this.  It's under MIT license so all good.

**Comment by Horndev** [comment]
I've not rolled out robohashes for non-custom profile pics :)
