### ISSUE TITLE
Downvote comments don't working

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#135]
**Describe the bug**
Can not downvote comments.

**To Reproduce**
1. Open comments in any post.
2. Click downvote icon in any comment.

**Expected behavior**
A window should be appear for input a satoshi and the vote button.

**Desktop (please complete the following information):**
 - Google Chrome 71.0.3578.98 on openSuse Tumbleweed
- Firefox 62.0.2 on Debian Testing/Sid

**Smartphone (please complete the following information):**
I'm not a tested on a mobile devices.

**Comment by Horndev** [comment]
Should now be fixed.
