### ISSUE TITLE
Quotation selected text

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#161]
On the one polish social media web is a curious function - quotation selected text. How it working?

You select text from another answer and you click reply button. Website automatically copy selected text to comment window and select user from which comment you copied the text.

You have a gif presented how work this function. (thanks @fervi)

http://185.238.72.170/mirko2.gif

**Comment by Horndev** [comment]
A pretty common feature - should be easy enough to implement.

**Comment by Horndev** [comment]
This feature is now implemented for quoting from posts.

TODO: implment for quoting/responding to comments.

**Comment by Horndev** [comment]
Now implemented for comments too.
