### ISSUE TITLE
Change reply function

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#162]
Currently if we reply the comment it this comment is  a nested one. Many people from community believes that the answer options should not nest comments, just call the user we answer.

How would it work?

Remove left margin and after the click reply button selected call the user who you responds to the comment.

You have a gif presented how work this function. (thanks @fervi)

http://185.238.72.170/mirko2.gif

**Comment by Horndev** [comment]
This is the difference between threaded conversations and flat conversations.

https://en.wikipedia.org/wiki/Conversation_threading

If we want to have comments scored and ranked, we have to have threaded conversations.  That is, higher scoring comments on top.  This is particularly important if we want to "bury" or hide low scoring comments.

If we go to flat, you will have good comments and bad comments interspersed.  There is no way to moderate a flat discussion aside from deleting comments (which we will not do).

I could make it a user option to show comments as flat - but you will see that it is not as effective for the vision of the website.

**Comment by DocBox12** [comment]
I think that comments with low scoring should be invisible. User should  have a choose  displaying them or not. This option should be default activate.

**Comment by Horndev** [comment]
I added some additional improvementes in the comments and replies as a pre-cursor for this feature.  In progress - but not done yet.

**Comment by Horndev** [comment]
I've updated the comments system, but still only have threaded comments.  They are now collapsable so it should work better than before.  An option for collapsing threads will be deferred to a future release of zapread.

**Comment by Horndev** [comment]
Closing this issue as I have not heard any complaints about comment threading for a long time.  If a change is required - It can be reconsidered.
