### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by fervi** [Horndev/zapread.com#23]
I think it's great if there was a system of simple achievements for using the platform. It could motivate people to use it.

An interesting option would be (but I do not know if you want to enter) a small reward for their achievement, e.g. 500 satoshi.

Many social networks (Steem, Wykop.pl and others) have such a system.

**Comment by Horndev** [comment]
Yes, I like this.  I was initially thinking of group-level achievements (not yet implemented), but individual level achievements should also be implemented.

Please reply with ideas for possible achievements you would like to see implemented.
