### ISSUE TITLE
Users can't use ZapRead with Tour and Popup

### ISSUE THREAD

**Issue by fervi** [Horndev/zapread.com#341]
Well, I can't reproduce, but some people give me a screenshots
![image](https://user-images.githubusercontent.com/2242925/58254235-9a492100-7d6a-11e9-9644-cca147ff4b2f.png)

It is probably logic bug - if left top popup is loader before center popup - but it's the theory

**Comment by Horndev** [comment]
Thanks for letting me know!  It looks like the buttons are missing somehow in that screenshot.  

I'm thinking I may disable the welcome tour and make that optional so it doesn't get people stuck like this.

**Comment by Horndev** [comment]
Just updating on this issue - I've disabled the tour for now.

**Comment by fervi** [comment]
Removing critical, because it's not critical anymore :D

**Comment by Horndev** [comment]
I've decided to remove the tour entirely.
