### ISSUE TITLE
(DOM based?) XSS in Quote Function

### ISSUE THREAD

**Issue by Horndev** [Horndev/zapread.com#385]
Credit to fwtf

Steps to reproduce:
1. Make a post with a simple XSS payload as text like <img src onerror=alert(1)>
2. Mark this payload (maybe right-click)

The attack fires in the Quote Popup (the popover-body div) and when pressing reply it fires in the editor.

Mitigation:
Maybe entity escape the selected text? (< = &lt; , > = &gt; , " = &quot; ...)

**Comment by wfinn** [comment]
Can we close this now?
