### ISSUE TITLE
Toggle NSFW and Sticky for Any Post

### ISSUE THREAD

**Issue by Horndev** [Horndev/zapread.com#397]
credit: ftfw

Toggle NSFW and Sticky for Any Post

Steps to reproduce:
1. Toggle NSFW on your own post
2. Intercept request to /Post/ToggleNSFW
3. Edit the "id" parameter
4. Forward the request

**Comment by Horndev** [comment]
Can't do this for any post -

`post.UserId.AppId == userId || UserManager.IsInRole(userId, "Administrator")`

you can only toggle own posts (unless an admin)

**Comment by Horndev** [comment]
Checks don't seem to be working...

**Comment by Horndev** [comment]
Ok, I made some more changes and found a bug. 5b6701b21b184059d9fec9c4e0f45d798e89b493 Try it again?

Should be fixed.

**Comment by wfinn** [comment]
Seems to be fixed
