### ISSUE TITLE
Follow self & Chat with self

### ISSUE THREAD

**Issue by Horndev** [Horndev/zapread.com#425]
Credit: Unknown User

Should not be able to do that.

**Comment by wfinn** [comment]
This unlocks "First Following" & " First Followed", it also makes posts appear twice in feeds of users doing that.

**Comment by Horndev** [comment]
- [ ] Fix follow self
- [ ] Fix chat self

**Comment by wfinn** [comment]
> * [ ]  Fix chat self

Take a look at this possible fix: https://github.com/Horndev/zapread.com/compare/dev...wfinn:chat-with-self?expand=1

GetUserName() probably isn't enough and I should you something like this right?

```
                    var myusername = await db.Users
                        .Where(u => u.AppId == User.Identity.GetUserId())
                        .Select(u => u.Name)
                        .FirstAsync().ConfigureAwait(true);
                        
                    if (username.ToLower() == myusername.ToLower())
                    //Redirect to /Manage
```
