### ISSUE TITLE
Post count includes draft posts

### ISSUE THREAD

**Issue by matt24smith** [Horndev/zapread.com#467]
The post count for a user within a group can be inflated by saving many draft posts.
For example in the screenshot below, the vim group has only one post in it at the moment, but on my profile it says that I posted 9/9 of the group's posts since I made one post and then saved 8 draft posts

![image](https://user-images.githubusercontent.com/8880061/70843953-8e10d800-1e10-11ea-80c5-89798b3b2b66.png)

**Comment by Horndev** [comment]
Thanks - I'll patch this ASAP.
