### ISSUE TITLE
Request: Add Twitter Card meta tags to URLs that are served for posts and comments

### ISSUE THREAD

**Issue by sgornick** [Horndev/zapread.com#469]
When I Tweet out a URL that is for a ZapRead post or a comment to a post, I would like to see the content of the post appearing in a "Twitter card" that Twitter composes for me Tweet.  Currently, ZapRead doesn't appear to have Twitter Card support (supported by including a set of meta tags).  

When ZapRead.com provides the Twitter card meta tags, Twitter then adds additional information from the post (or comment) to my Tweet.  So even though I post only the URL, the Twitter card can show information pulled from that post (or comment), making it more likely a person viewing my Tweet will click on my URL (or on the "Twitter card", which is the same link/URL).  

Here's some info on Twitter cards:
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards

All the "cool kids" (Reddit, Steemit, Publish0x, Uptrennd, etc.) are doing it!

(It doesn't have to be just the Post and Comment URLs, even the FAQ, About, etc. URLs would benefit from supporting Twitter Card as well.

**Comment by Horndev** [comment]
Thanks very much for this suggestion.  I agree that I need to do this.  I'm not a big twitter user so I have some learning to do.  It looks easy enough to do.  I'll get right on it :)

**Comment by Horndev** [comment]
I've implemented this and it's now live.  I will improve it in the future, but the functionality is there.
