### ISSUE TITLE
UI: dynamic group link destroys itself

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#488]
On /Post/NewPost/, after changing the group, a href to the group contains @Url.Action("GroupDetail", "Group")

**Steps To Reproduce**
- go to /Post/NewPost/
- change group of post, then click somewhere else to trigger the change
- click on group name under "New Post in X" (or inspect)

**Expected Behavior**
The link should lead to the group.

**Comment by Horndev** [comment]
Fixed in New editor.
