### ISSUE TITLE
Special Chars in Post Title Make the Links with Title in Url Fail on /?sort=New

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#489]
**Special Chars in Post Title Make the Links with Title in Url Fail on /?sort=New**
1. Make a post with ' in the title
2. Go to /?sort=New
3. Click on the post title
4. Read "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Seems to be some unicode thing, as the url contains %25E2%2580%2599 instead of '

**Comment by Horndev** [comment]
Thanks - I've noted these urls throwing exceptions.  I have a fix in the works...

**Comment by Horndev** [comment]
Fixed in dd3d13114fa0dfa58d6c8a152e2ef5aae6a91238
