### ISSUE TITLE
DataTables warning from Spending Table

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#507]
When I go to /Manage/Financial I get the following alert:
```
DataTables warning: table id=spendingTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```
Everything but the spending history was loading correctly.

**Comment by wfinn** [comment]
Fixed with [this commit](https://github.com/Horndev/zapread.com/commit/453e9c7d8b345f9919f0c8276121bf214f45b775) I guess.

**Comment by Horndev** [comment]
Yeah - it was some tweaking I did and unit tests don't catch browser issues...
