### ISSUE TITLE
"Minification failed. Returning unminified contents."

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#540]
https://www.zapread.com/bundles/post/detail  (javascript) starts with this comment:
```
(41,32268): run-time error JS1004: Expected ';'
(41,32305-32310): run-time error JS1006: Expected ')': fetch
(41,32304): run-time error JS1004: Expected ';'
(41,32559): run-time error JS1004: Expected ';'
...
```

**Comment by Horndev** [comment]
It's an artifact of the bundler.  It's actually minified by babel now (something I've recently changed), but the ASP bundler is not smart enough to read it.  Maybe I can update the ASP bundler to resolve this.  It's not actually a problem.

Babel is just smarter than some other minifiers.

**Comment by wfinn** [comment]
> It's not actually a problem.

Ofc not, I just felt like adding a big (useless) comment to  a minified file defeats the purpose of minifying it :)
