### ISSUE TITLE
Editing Group of Post Fails

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#560]
Go to https://www.zapread.com/Post/Edit?postId={ID}, press Change Group, enter something, see the following error in the console.
`POST https://www.zapread.com/Group/GetGroups 404 edit.js:27`

**Comment by wfinn** [comment]
Is edit.js in dev or master up to date?

The minified version says
```
                            url: "/Group/GetGroups/",
                            type: "POST",
                            dataType: "json",
                            data: {
                                prefix: t.term
                            },
```
but on GitHub the data prefix thing is commented out and .term is appended to the url (as it should to fix this issue).
See https://github.com/Horndev/zapread.com/blob/master/zapread.com/Scripts/src/pages/post/edit.js#L129

**Comment by Horndev** [comment]
This bug is fixed in the new editor.
