### ISSUE TITLE
[Major] 0 Satoshi invoices do not increase account balance.

### ISSUE THREAD

**Issue by IntinteDAO** [Horndev/zapread.com#567]
If you generate 0 satoshi (any value) on Zapread Invoice and pay for it, the transaction will officially take place, but you will not get these funds into your account. Probably the function checks if the transaction has been successful, but it does not check (for 0 satoshi) how many funds have been transferred.

**Comment by Horndev** [comment]
Yeah - I don't handle 0 satoshi invoices.  A newer version of LND seems to allow them to be generated now.  Older version threw an error when you tried it.  I'll have to fix this ASAP!

I think the proper behaviour is to read the invoice and credit the amount paid.

**Comment by Horndev** [comment]
related to #113
