### ISSUE TITLE
Pasting image from clipboard - sometimes failure

### ISSUE THREAD

**Issue by IntinteDAO** [Horndev/zapread.com#579]
Sometimes uploading photos from the clipboard does not work correctly by throwing out an alert with such content.
http://meshnet-users.tk/paste/p/hpbb/l.txt

**Comment by Horndev** [comment]
Thanks for the bug report.

Which browser / os?

**Comment by IntinteDAO** [comment]
Firefox 68.8.0esr
I think it's Devuan Ceres (Well, it's now my primary computer, but it shouldn't be XD)

**Comment by Horndev** [comment]
The editor has been updated.  I will monitor if this bug manifests again.
