### ISSUE TITLE
Not link in notification about comment reply

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#59]
**Describe the bug**
If someone answers our comment and means us, we get a notification about the answer without a link to the entry. You can not go through to the entry in which we received a response to the comment.

**To Reproduce**
1. Find an entry and comment on it.
2. Wait for someone to answer you by tagging you
3. You will receive a notification in which there is no link to the entry.

**Expected behavior**
The notification should contain a link to the entry in which someone has marked us in the comment. This works correctly for alerts about new entries.

**Screenshots**
![post](https://user-images.githubusercontent.com/46194605/50546859-12ce0a80-0c2f-11e9-81f9-ed6e31a83f49.png)

**Desktop (please complete the following information):**
- operating system: openSUSE Tumbleweed
- browser: Google Chrome 71.0.3578.98

**Smartphone (please complete the following information):**
Not checked on smartphone.

**Additional context**

**Comment by Horndev** [comment]
Thanks for the bug report.  I will make updates soon.

**Comment by Horndev** [comment]
This particular bug is fixed in https://github.com/Horndev/zapread.com/commit/96a67676c6ec91b36c372a3c00d7337d1950a518

Still need to overhaul the entire messaging system for more complete information and better appearance.
