### ISSUE TITLE
The editor panel is pinned while scrolling the screen

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#63]
When creating a long post, the text input window is a extended, but formatting panel is in one place at all time. This means that if you want to format a part of the text, you have to select it, scroll the whole window up and you can use the formatting panel. I think the formatting panel should "follow us" during scrolling window with the mouse. If I am not mistaken, this solution is in wordpress.

**Comment by Horndev** [comment]
update from Zapread:

![image](https://user-images.githubusercontent.com/908867/51147018-23859f80-182f-11e9-9bb9-5b1c66468a5a.png)

**Comment by Horndev** [comment]
This is fixed in https://github.com/Horndev/zapread.com/commit/ff35530a3ad0b9539c23eeb0111fdc2623d08890
