### ISSUE TITLE
@writ4personalit Account Login Failure

### ISSUE THREAD

**Issue by writ4personalit** [Horndev/zapread.com#634]
There is usually a failure on logging into my Zapread.com account, @writ4personalit. I noticed that the sending of "rocketmail (Yahoo email) for My verification" isn't working at all.
There is an "error message interface" all the time. I need your quick response over tackling my problem. I haven't been able to access my Zapread.com profile due to health and financial reasons for a long time.
I hope to return back to self-publishing as early as possible. My contact email address is: gboyegaogunmola@rocketmail.com. My real name is: Adegboyega Ogunmola.
I have inserted the screenshot of the error message given out while logging in and even when trying to contact the Zapread Support Team from the website.
![Screenshot_20210819-172911](https://user-images.githubusercontent.com/91076033/134028209-756cfc3c-d5aa-4a2d-8c15-a6d790d2ebf7.png)

**Comment by Horndev** [comment]
Thank you for the report.  I have an issue with the email which will be resolved with a future platform update.

**Comment by writ4personalit** [comment]
Thanks so much for what you have been doing for me over this issue, @Horndev. There is failure of logging into my Zapread.com (Account) Profile Interface. I am grateful indeed for adding my issue to the To do in 0.4-beta, via automation on September 28th, 2021.

Recently, I wanted to self-publish through my Zapread.com profile. I feel I am losing out from the work I haven't been able to get done. I have recovered a lot after the financial and health problem. I had to retire voluntarily from my public service appointment some years ago.

I still have to contact you, because I haven't any idea of the likely date for the 0.4-beta. The Zapread.com Website Upgrade to the next level may take a considerably long time.

Firstly, I want to know about the possibility of Logging In through My Google or GitHub Account. I would have done it myself. I am not sure about getting logged into my old account.

Secondly, do you think it will be better for me to wait until the 0.4-beta Software Upgrade. Can I have any information about when the next upgrade (0.4-beta) is coming up.

Thanks again, @Horndev. I really appreciate your assistance all the time. I still need your kind support and assistance.

I will be expecting your reply as early as possible.

**Comment by Horndev** [comment]
I made an update to the website, not sure if it fixed your problem.  I'm going to be fixing lots of bugs in the next while, and adding more features.  I appreciate you letting me know about your issues here.

Please let me know if you can log in.

**Comment by writ4personalit** [comment]
Good day to you, @Horndev,Thanks so much for considering me on Zapread.com. I have logged into my account ***@***.***) interface successfully.I really appreciate your kindness and consideration for me. I feel so grateful over this kind support. I really logged in and even published an article.But, I decided to change my autogenerated profile image with the latest one. I discovered that it only replaced the old image, which I didn't need anymore. I have noticed that several development upgrades are getting deployed to the Zapread platform recently.I think you should take note of this issue, because it may be affecting many people. I have resorted to using the old profile image, until there is a chance to replace it with the latest one.I hope Zapread.com will continue developing. I noticed that the whole editing interface has changed. I wish you more grace to your elbow. I believe the next oncoming version will be deployed soon. Kudos!Thanks once again, Mr Steven Horn. I feel grateful over your consideration.On Jan 9, 2022 9:40 PM, Steven Horn ***@***.***> wrote:
I made an update to the website, not sure if it fixed your problem.  I'm going to be fixing lots of bugs in the next while, and adding more features.  I appreciate you letting me know about your issues here.
Please let me know if you can log in.
