### ISSUE TITLE
Investigate User Profile Image Changing

### ISSUE THREAD

**Issue by Horndev** [Horndev/zapread.com#647]
**Describe the bug**

Reported by user:
"I decided to change my autogenerated profile image with the latest one. I discovered that it only replaced the old image, which I didn't need anymore. I have noticed that several development upgrades are getting deployed to the Zapread platform recently.I think you should take note of this issue, because it may be affecting many people. I have resorted to using the old profile image, until there is a chance to replace it with the latest one."

**Comment by wfinn** [comment]
I believe it's this v counter that's off. And in chat it always seems to use v=0 for the first message. I'm at v=8 and it just got set to v=1 when trying.

**Comment by Horndev** [comment]
I'm looking into this now...

**Comment by Horndev** [comment]
Fix should now be merged in.
