### ISSUE TITLE
No admin on the created group

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#68]
An unusual error. I created group in zapread.com named linux-poland (http://zapread.com/Group/GroupDetail/38) and I have a moderator permission, but not have admin permission. 

Similarly I created group android-polish (http://zapread.com/Group/GroupDetail/41), but I have admin and moderator permission.

I don't know what a bug and.

**Comment by Horndev** [comment]
It looks like the linux-poland group was created before I fixed a bug where the creator was not an admin.  I have granted you admin.  All groups now created will give admin to the creator automatically.

Thanks for reporting the problem!  If you see any other groups without admins, just let me know and I'll go and fix it.

**Comment by DocBox12** [comment]
I have a new informations about groups without administrators. Below list:

| Group name | Administrator | Group profile link | Administrator profile link |
|-------|--------|--------|------|
|Poland|fervi|http://zapread.com/Group/GroupDetail/35|http://zapread.com/user/fervi
|Poland - Strok|cyberpunkbtc|http://zapread.com/Group/GroupDetail/34|http://zapread.com/user/cyberpunkbtc
|bitcoin-poland|m00n|http://zapread.com/Group/GroupDetail/32|http://zapread.com/user/m00n

**Comment by Horndev** [comment]
They should all be fixed now.  Thanks! 

There will be more admin features coming as well.  Please feel free to make requests :)
