### ISSUE TITLE
Button "my groups"

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#69]
It would be nice to add button named "My groups". After clicked the button all groups that we are members would appeared. The button can be placed example between nick and balance satoshi.

**Comment by Horndev** [comment]
yes, I see the need for some more navigation support.  I will work on a better design for the navigation bar.

For now, you can see your groups if you go to the manage page: https://www.zapread.com/Manage and scroll down to the groups section on the left.

Thanks!

**Comment by Horndev** [comment]
Groups are now on home page.
