### ISSUE TITLE
The Join button in the group in which we are already

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#70]
**Describe the bug**
If you get in group which you are member instead of the Leave button, the Join button is located. 

**To Reproduce**
Click Groups link
Join a somebody group, example Travel, clicked Join button.
Click travel group.
You see Join button instead Leave button

**Expected behavior**
If you a members, you can see Leave instead Join button.

**Screenshots**
![1](https://user-images.githubusercontent.com/46194605/50589383-b9601880-0e86-11e9-976d-8e8193a82f79.png)
![2](https://user-images.githubusercontent.com/46194605/50589395-bebd6300-0e86-11e9-8536-04f410a4a671.png)

**Desktop (please complete the following information):**
- Google Chrome 71.0.3578.98 x64
- openSUSE Tumbleweed

**Smartphone (please complete the following information):**
I have not tested on smartphone.

**Comment by Horndev** [comment]
Nice catch.

Problem fixed in patch: https://github.com/Horndev/zapread.com/commit/3d21609e194aebe7f5ea0462fa484a83694f41db

fix is live.
