### ISSUE TITLE
Editor in chat is broken

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#728]
I opened our chat and was greeted with this:

![Screenshot 2022-02-28 at 20-45-09 Chat with Zelgada](https://user-images.githubusercontent.com/42862612/156048505-7a755daf-4136-4690-848d-25790d076948.png)

(The header in the middle is due to firefox screenshots)

**Comment by Horndev** [comment]
Yeah, CSS purge isn't very smart.  Reverting now.
