### ISSUE TITLE
Inputed text in messages window is under formatting panel.

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#74]
**Describe the bug**
Inputed text in messages window is under formatting panel.

**To Reproduce**
1. Enter the profile any user.
2. Click message button.
3. Enter the any text.

**Expected behavior**
The input text should below the formating panel. 

**Screenshots**
![message](https://user-images.githubusercontent.com/46194605/50638516-52ae2e00-0f5e-11e9-823c-4ce4c9761ce6.png)

**Desktop (please complete the following information):**
- Google Chrome version 71.0.3578.98
- openSUSE Tumbleweed

**Smartphone (please complete the following information):**
 I am not tested this bug on smartphones.

**Comment by Horndev** [comment]
Should be fixed as of patch: https://github.com/Horndev/zapread.com/commit/889506c80eb7feadf9153db961f72e6358493060
