### ISSUE TITLE
Security: /Img/GroupIcon/ 

### ISSUE THREAD

**Issue by wfinn** [Horndev/zapread.com#741]
Just so you don't forget the second /Img/ thing as I dont see it addressed in #734
The /Img/GroupIcon/ bug is still there, more details in chat.
Should have made 2 issues for these 2 from the beginning.

**Comment by Horndev** [comment]
Can you double check this?  I think I added some code to deal with that.

**Comment by wfinn** [comment]
Yes you're right my bad
