### ISSUE TITLE
My post doesn't work

### ISSUE THREAD

**Issue by IntinteDAO** [Horndev/zapread.com#822]
https://www.zapread.com/p/2bT/pinephone-scrap-phone

![obraz](https://user-images.githubusercontent.com/56807194/177299603-b6b024f4-c0b5-4ae3-bbb2-79e1d6a3880d.png)

**Comment by IntinteDAO** [comment]
I think all articles don't work

**Comment by Horndev** [comment]
Closing this issue since the link above works now.

**Comment by IntinteDAO** [comment]
Yes, sorry :P Works
