### ISSUE TITLE
Copy a link to post

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#88]
You can add the option to copy a link to a post in the Share function along with the icon. Example of the icon:

https://www.iconfinder.com/icons/216660/link_icon

![copy](https://user-images.githubusercontent.com/46194605/50639569-390ee580-0f62-11e9-9622-70166ed06a58.png)

**Comment by Horndev** [comment]
Now implemented.

![image](https://user-images.githubusercontent.com/908867/53709090-bf359400-3e0c-11e9-92e5-566c2b6967f9.png)
