### ISSUE TITLE
The link in notification not move us to new site.

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#93]
**Describe the bug**
After clicked on bell and link we has we will be moved to post. If we clicked on bell again but other link this then we will not be moved to the new site but it will only be refreshed currently displayed.

**To Reproduce**
You must have minimum 2 notifications.
1. Click the bell and choose one of the links.
2. You will be moved to the post.
3. Click the bell and choose other the link.
4. You will not be moved to the post, but currently visible site will be refreshed.

**Expected behavior**
After click on other link we should moved to new site.

**Desktop (please complete the following information):**
- Google Chrome  71.0.3578.98
- Firefox 64.0
OS: opensuse Tumbleweed

**Smartphone (please complete the following information):**
I am not tested in mobile devices.

**Comment by Horndev** [comment]
Fixed.
