### ISSUE TITLE
Sending private messages not work in Firefox

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#99]
**Describe the bug**
Sending private messages not work in Firefox. After click on send button nothing happens.

**To Reproduce**
1. Open zapread.com in Firefox.
2. Open any user profile and click Message button.
3. Write a any message and click Send button.
4. Message has not sending and message window is not hide.

**Expected behavior**
Sending message should good working in Firefox browser.

**Desktop (please complete the following information):**
- Firefox 62.0.2 on Debian Buster / Sid - not working.
- Firefox64 on openSUSE Tumbleweed - not working
- Chromium and Chrome - all good working

**Smartphone (please complete the following information):**
I am have not tested on the mobile devices.

**Comment by Horndev** [comment]
This is now fixed.  I will monitor for changes and re-open if needed, but I fixed the code causing the errors and it worked for me in FF.

**Comment by DocBox12** [comment]
I wrote a post about bug (polish only). If I get some information about errors and repeat them, I will report them on github.

[https://www.zapread.com/Post/Detail/1652](url)

**Comment by Horndev** [comment]
@DocBox12 thanks!  I really appreciate it!
